# 工作流的名称
name: Deploy Hugo site to Pages

# 触发工作流的事件
on:
  # 当推送到 main 分支时触发
  push:
    branches:
      - main  # 或者 master，取决于你的主分支名称
  # 允许你从 Actions 标签页手动触发此工作流
  workflow_dispatch:

# 工作流执行的任务
jobs:
  # 定义一个名为 "deploy" 的任务
  deploy:
    # 任务运行的虚拟环境
    runs-on: ubuntu-latest
    
    # 任务执行的步骤
    steps:
      # 步骤1: 检出你的源代码仓库
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # 拉取 Git 子模块 (我们的主题)
          fetch-depth: 0    # 获取所有历史记录，以便 Hugo 生成 lastmod 等信息

      # 步骤2: 设置 Hugo 环境
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # 或者指定一个版本，如 '0.111.3'
          # extended: true # 如果你的主题需要 Sass/SCSS 功能，请取消此行注释

      # 步骤3: 构建网站
      - name: Build
        run: hugo --minify # 运行 hugo 命令生成静态网站，并压缩文件

      # 步骤4: 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用我们之前设置的部署密钥
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # 要部署到的目标仓库git add .
          external_repository: yukari502/yukari502.github.io 
          # 要部署到的目标分支 sdf
          publish_branch: main # 或者 master
          # 要发布的内容所在的目录 (Hugo 默认生成到 public)
          publish_dir: ./public
          # 提交信息
          commit_message: ${{ github.event.head_commit.message }}